// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0AtYSU4OXO6fVogheRqag1kP3bgG-R0Q',
    appId: '1:714025477305:web:e6ff6220d4abdda26be768',
    messagingSenderId: '714025477305',
    projectId: 'emart-4b840',
    authDomain: 'emart-4b840.firebaseapp.com',
    storageBucket: 'emart-4b840.appspot.com',
    measurementId: 'G-VQFNMF4FCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0crizkaEILx1zIEmFymGsI4IaAJTtvUk',
    appId: '1:714025477305:android:be5c1ca6f6784aac6be768',
    messagingSenderId: '714025477305',
    projectId: 'emart-4b840',
    storageBucket: 'emart-4b840.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSJGsiS7zhej7XtaAlunQrogDikLTeKvk',
    appId: '1:714025477305:ios:721cac43de5052f96be768',
    messagingSenderId: '714025477305',
    projectId: 'emart-4b840',
    storageBucket: 'emart-4b840.appspot.com',
    iosBundleId: 'com.example.playStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSJGsiS7zhej7XtaAlunQrogDikLTeKvk',
    appId: '1:714025477305:ios:d5891742e447bac26be768',
    messagingSenderId: '714025477305',
    projectId: 'emart-4b840',
    storageBucket: 'emart-4b840.appspot.com',
    iosBundleId: 'com.example.playStore.RunnerTests',
  );
}
